### ISSUE TITLE
KDE notification system

### ISSUE THREAD

**Issue by nono313** [mhogomchungu/qCheckGMail#26]
Hi,

Would it is be possible to get a notification in the KDE notification system when a new e-mail arrive instead of just displaying the icon ?
It would be great to be also able to configure it through the system configuration to add special command to execute when a new mail arrive (for example setting a notification LED)

Regards

**Comment by mhogomchungu** [comment]
right click on the application icon->configure options->audio notify.

is the option ticked?

if the option is ticked,then you should be able to get notifications using KDE notification system including audio notifications.

If you are into programming,the function that is called to use KDE notification system to play audio sound is here: https://github.com/mhogomchungu/qCheckGMail/blob/ee6ac9a7127832197d3dba99e21dad3a065a87a9/src/statusicon.cpp#L158

**Comment by mhogomchungu** [comment]
It seems a bug was introduced at some point,i just tested it and it also didnt work.I never noticed it because i dont use the feature.

the git version should now work as you expect. Will appreciate if you can confirm.

**Comment by nono313** [comment]
Is it suppose to add a new section in "source of event" in the notification system configuration ?
If so, then I still don't have it, even with the latest version from git and the option checked.

**Comment by mhogomchungu** [comment]
yes,

if you have already installed the git version,then close system settings and restart it again.

[IMG]http://i59.tinypic.com/opwykp.jpg[/IMG]

**Comment by nono313** [comment]
Unfortunately, I still don't have anything.
I'm running Kubuntu 14.10.

**Comment by mhogomchungu** [comment]
log out and then log back in and then look at the list one entry at a time to see if its still not there.

will install Kubuntu 14.10 to check for myself where the problem is if you report the above still not working.

**Comment by nono313** [comment]
Still nothing.
I have just seen that the autostart feature doesn't seem to work either.

**Comment by mhogomchungu** [comment]
below link has kubuntu 14.10 using plasma 4 and plasma 5,which one are you using?

http://www.kubuntu.org/getkubuntu

**Comment by nono313** [comment]
When I look at KDE Help I have "4.14.1", so I guess that's Plasma 4.
I juste did an upgrade from 14.04 a few months ago and as plasma 4 edition seems to be the stable one that's probably what I have.

**Comment by mhogomchungu** [comment]
The git version should now work,can you confirm?

The problem was that the notification file was stored at "/usr/share/apps/qCheckGMail/" while kubuntu expected it to be at "/usr/share/kde4/apps/qCheckGMail/"

build qCheckGMail with install prefix of "/usr" to make sure the notification file is installed at:
```
/usr/share/kde4/apps/qCheckGMail/qCheckGMail.notifyrc
```

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=release .

**Comment by nono313** [comment]
On my machine, 'kde4-config --prefix' gives me '/usr' so both command do the same thing.

I have just tried, it's working now.
Thank you very much and especially for your fast answer
