### ISSUE TITLE
Autostart fails on Debian Testing (non kde build)

### ISSUE THREAD

**Issue by bas-t** [mhogomchungu/qCheckGMail#29]
Hi, as the title says, autostart fails on stretch (testing). Both qt4 and qt5 non kde builds tested.
However when I wait some time and start qCheckGMail myself, it functions just like it should.
Sadly I don't have any clue yet, hence this ticket.
On Debian Jessie (stable) all is still very fine.

Regards,
Tycho.

**Comment by bas-t** [comment]
Hm, at least with the qt5 build it does start, but fails to show the systray icon. Even mplayer works.
Killing it and manually starting it again afterwards will show th systray icon.
Still no clue as to why the systray icon fail to show.

**Comment by mhogomchungu** [comment]
What desktop environment are you using?

The problem could be caused an updated version of the desktop environment you are using having a different way of auto starting applications.

Will also appreciate a link to an debian testing image file if they are available. Its better if you give me a link if one exists that me looking for one to reduce the likelihood of using two different images.

**Comment by bas-t** [comment]
I'm using Mate desktop. Indeed the version is different. Jessie uses 1.8 while Stretch uses 1.10
Not sure what you mean by image file. I always install my Debian versions with a pxe netboot procedure. But you can do the same thing using an iso (this one is an amd-64 netboot iso):
http://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso

**Comment by bas-t** [comment]
Oh, I see, regarding the image. I just installed fresh using my pxe boot server today, so installing with that iso and run apt-get dist-upgrade should get you exactely where I am.

**Comment by mhogomchungu** [comment]
I cant seem to be able to reproduce your issue,running mate 1.10.2 from an installation image you provided above and qCheckGMail icon consistently show up.

The icon consistently failed to show in cinnamon 2.6.13 and it started to consistently show after i added a five second delay in its startup time.

Tested both with Qt4 build.

I cant seem to be able to reproduce your issue in mate.

**Comment by bas-t** [comment]
Thanks for testing!
Did you use that 5 seconds startup delay in mate too?

Op 30-12-15 om 11:46 schreef mhogomchungu:

**Comment by mhogomchungu** [comment]
I am testing in mate without adding any delays or changing anything.

Strange,i started the computer and logged in to mate and the icon did not show up,i logged out and logged back in and the icon did show up and it consistently show up every time i log out and log in.

I restarted the computer again and the icon show up on first log in and it consistently show up every time i log out and log back in.

It will be hard to try to fix a problem with this level of inconsistency. Do you have another Qt tray application in your computer and if you do,does it show the same behavior?

I am doing the tests in virtualbox but i dont think this affects the inconsistent results i am seeing.

**Comment by bas-t** [comment]
Well, on my machine no inconsistency whatsoever. Both qt4 and qt5 builds start (I can hear it's sound alert for new messages) but never show the systray icon. Same behaviour on logout and login again.

Besides qCheckGMail, I only have a volume controll icon in the systray wich is, afaik, not qt. Should it be qt after all: it always behaves normal on startup.

So now I set a delay for qCheckGMail (I just rename it and put a startup bash script in it's place with sleep 10), and that is a good workaround for the problem. qCheckGMail always starts and shows the icon.
Mind you, there are more strange startup things in Debian Stretch. I suspect that systemd is to blame. Can't be sure though...
Let's hope this will improve over time, still about 16 months to go before Stretch will be released.

I think we better let it rest for about six months or so and review the situation at that time.
Or are you determined to get to the bottom of this right now?

**Comment by mhogomchungu** [comment]
The inconsistencies i am seeing are best explained with a race condition somewhere and i also suspected that a delay of some time will solve the problem.

I am closing this one for now but will keep looking around if this is a known problem and if there is anything i can do on my side to avoid the problem.
