### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by poofleesni** [mhogomchungu/qCheckGMail#31]
Could you add OAuth2 support (by [kaccounts](https://github.com/KDE/kaccounts-integration) or some other way)?

**Comment by mhogomchungu** [comment]
Could you provide a link to a service i should use for testing when i implementing this request.

**Comment by poofleesni** [comment]
I'm not sure what you mean by "service". I meant using OAuth2 for [gmail](https://developers.google.com/gmail/xoauth2_protocol#using_oauth_20). You can check example implementation with kaccounts [here](https://github.com/anthon38/gmailfeed/tree/kaccounts). I don't know how much it helps you since it's only plasmoid not a standalone app like yours.

**Comment by mhogomchungu** [comment]
Having a working example will surely work.

My initial comment was due to me thinking you wanted this functionality not to access google mail but to access a password storage service that hosts your gmail password because you are hosting them in the cloud for some reason.

Having a working example of kaccount usage will surely help.

**Comment by mhogomchungu** [comment]
I have looked at the project you linked to and it seems the difference in how we access google.

The project uses tokens[1] while mine uses username+password[2].

The easiest thing to do will probably be to give users an option to provide these tokens instead of username+password if they can be found easily.

What desktop environment are you using and are you using pure Qt version of qCheckGMail or qCheckGMail+KDE integration?

[1] https://github.com/anthon38/gmailfeed/blob/d47f34cf5b79ba0df18bbb26e6c9ff125361c875/plugin/account.cpp#L61

[2] https://github.com/mhogomchungu/qCheckGMail/blob/bbe62bb5d8534944cf6f11bcf3c746f65253651f/src/qcheckgmail.cpp#L754

**Comment by poofleesni** [comment]
I'm using qCheckGMail+KDE  (kf5 build) on KDE 5.6.

I think the whole point of OAuth2 is to use token instead of username/pass. If I understand this correctly it's Kaccounts role to make authentication and store passwords/tokens with "Single Sign On" or SSO, SignOn framework and the role of qCheckGMail would be only to notify on new emails.

In case of gmailfeed it depends on kaccounts-providers, kaccounts-integration and intltool packages and it registers itself with [this](https://github.com/anthon38/gmailfeed/blob/kaccounts/plugin/google-gmail.provider.in) in /usr/share/accounts/providers and [this](https://github.com/anthon38/gmailfeed/blob/kaccounts/plugin/gmail-feed.service.in) in /usr/share/accounts/services.

Of course it will by only usable with qCheckGMail+KDE integration. I have found library for pure [QT](https://github.com/pipacs/o2) instead of kaccounts also. I don't know if there is any working example.

**Comment by mhogomchungu** [comment]
I just made a commit that makes it possible to use OAuth2 tokens[1].

All the code that deals with requesting tokens is here[2] if you are interested.

There is currently no GUI way to set things up and qCheckGMail currently asks for what is called "refresh token". When setting up and account,use the "refresh token" as a password and then tick the check box labeled "password is google's refresh token".

You can get your "refresh token" by doing what is documented in this link[3] where i got all the documentation i needed.

The link has a python program named ```oauth2.py```,download the program and run it to get the "refresh_token".

The section to look at is named ```Creating and Authorizing an OAuth Token```

qCheckGMail secret key is: ```LRfPCp9m4PLK-WTo3jHMAQ4i```
qCheckGMail cliend ID is" ```90790670661-5jnrcfsocksfsh2ajnnqihhhk82798aq.apps.googleusercontent.com```

Ask if you get stuck anywhere while trying to get the token.

Will make a GUI to do these steps automatically but it wont be any time soon.

[1] https://github.com/mhogomchungu/qCheckGMail/commit/18ffae5c210a58fae006ac1e0637b45d3fef8b8b

[2] https://github.com/mhogomchungu/qCheckGMail/blob/18ffae5c210a58fae006ac1e0637b45d3fef8b8b/src/qcheckgmail.cpp#L762

[3] https://github.com/google/gmail-oauth2-tools/wiki/OAuth2DotPyRunThrough

**Comment by poofleesni** [comment]
It works well but only if using with one account. After adding second account it's unable to connect (both accounts work alone).

**Comment by mhogomchungu** [comment]
Can you update from git and try again.

**Comment by poofleesni** [comment]
Now it's segfault instatnly
`qCheckGMail[910]: segfault at 10 ip 00007f13a48275c0 sp 00007ffdf229cba8 error 4 in libKF5Notifications.so.5.22.0[7f13a4808000+51000]`

Process 910 (qCheckGMail) of user 1000 dumped core.

Stack trace of thread 910:
#0  0x00007f13a48275c0 _ZN19KStatusNotifierItem11setCategoryENS_12ItemCategoryE (libKF5Notifications.so.5)
#1  0x0000562f006df4d3 _ZN11qCheckGMailC2ERK7QString (qCheckGMail)
#2  0x0000562f006d89d5 n/a (qCheckGMail)
#3  0x0000562f006d8535 main (qCheckGMail)
#4  0x00007f13a1e01741 __libc_start_main (libc.so.6)
#5  0x0000562f006d8829 _start (qCheckGMail)

Stack trace of thread 913:
#0  0x00007f13a1ebf68d poll (libc.so.6)
#1  0x00007f139d55cae2 n/a (libxcb.so.1)
#2  0x00007f139d55e757 xcb_wait_for_event (libxcb.so.1)
#3  0x00007f1395673a79 n/a (libQt5XcbQpa.so.5)
#4  0x00007f13a2ad81d8 n/a (libQt5Core.so.5)
#5  0x00007f13a1bcb474 start_thread (libpthread.so.0)
#6  0x00007f13a1ec869d __clone (libc.so.6)

Stack trace of thread 916:
#0  0x00007f13a1ebf68d poll (libc.so.6)
#1  0x00007f139ed74fd6 n/a (libglib-2.0.so.0)
#2  0x00007f139ed750ec g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f13a2d0472f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f13a2cac4ca _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f13a2ad32f3 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f13a2ad81d8 n/a (libQt5Core.so.5)
#7  0x00007f13a1bcb474 start_thread (libpthread.so.0)
#8  0x00007f13a1ec869d __clone (libc.so.6)

Stack trace of thread 915:
#0  0x00007f13a1ebf68d poll (libc.so.6)
#1  0x00007f139ed74fd6 n/a (libglib-2.0.so.0)
#2  0x00007f139ed750ec g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f13a2d0472f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f13a2cac4ca _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f13a2ad32f3 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f139fd46a65 n/a (libQt5DBus.so.5)
#7  0x00007f13a2ad81d8 n/a (libQt5Core.so.5)
#8  0x00007f13a1bcb474 start_thread (libpthread.so.0)
#9  0x00007f13a1ec869d __clone (libc.so.6)

**Comment by mhogomchungu** [comment]
The latest git has a fix for the crush.

I didnt notice the crash because i am using the pure Qt version.

**Comment by poofleesni** [comment]
Wow everything works now!. Thanks for your support.

**Comment by mhogomchungu** [comment]
You are welcome.

You should know that usage of tokens takes two network access for every check where as username+password takes only one so your usage of tokens doubles your network usage.

**Comment by mhogomchungu** [comment]
You should also try the pure Qt build.

The tray bubble looks best with KD4 integration,second best pure Qt application and worse with KF5 integration because KF5 removed some html tags that made it possible to structure texts on the tray bubble: https://github.com/mhogomchungu/qCheckGMail/issues/28

**Comment by poofleesni** [comment]
I'm fine with it for now. Is pure Qt build working with KF5 version of kwallet?

The only issue for me is lack of HIDPI support in edit account dialog which is barely readable (dialog is too small, there is no vertical space for description of all rows).. But that's a minor thing, non relevant since I'm done with it.

**Comment by mhogomchungu** [comment]
No kwallet integration with Qt version.

Could you post a picture of the dialog.

After you have taken a picture with ksnapshot or any other tool,drag and drop it here to "attach" it

**Comment by poofleesni** [comment]
![qcheckgmail](https://cloud.githubusercontent.com/assets/19184145/15651844/6281ec08-2682-11e6-8c53-86cba6bb035a.png)

**Comment by mhogomchungu** [comment]
Wow!!!

Below is how the GUI looks like here.

Not sure what i can do about that,maybe making the GUI stretchable??

![Uploading qCheckGMail.jpeg…]()

**Comment by mhogomchungu** [comment]
Could you update your sources and see if there is an improvement in how GUI look? They can go full screen now.

**Comment by poofleesni** [comment]
Much better now, thanks!

**Comment by mhogomchungu** [comment]
The git version now has a GUI way to set things up.

I am closing this one as "fixed".

**Comment by mhogomchungu** [comment]
You should update to the latest git version because it does things a bit more efficiently now.
