### ISSUE TITLE
Improve OAuth2 functionality to reuse access token until it expires and make client ID and secret configurable

### ISSUE THREAD

**Issue by vvv-ibm** [mhogomchungu/qCheckGMail#33]
Hi,

great job on the OAuth2 support, works perfect to eliminate annoying suspicious login messages when I travel!

Any chance you can change the logic to re-use the access token instead of creating a new one every time you check for new mail? The access token is usually valid for an hour and it looks a bit excessive to re-generate it every 5 minutes or less. It should be straight forward to keep the expiration time of the token in memory and check it before using it.

Also, if you could make the Google client ID and secret configurable so that I can use my own (I already rebuilt the code with mine but it would be nicer not to have to maintain code :) ?

Thanks!

**Comment by mhogomchungu** [comment]
Its now possible in the git version to set client ID and client Secret.

After you have updated from git,run the application once and the configuration file will have two more entries named "clientID" and "clientSecret". Set your values and restart the application to use them.

The config will will probably be at "~/.config/qCheckGMail/qCheckGMail.conf"

Yes,i am away of the inefficiency in how access token is being obtain and i plan to solve it some time in the near future.

**Comment by mhogomchungu** [comment]
Current git version now reuses access token until it expires and then asks for a new one.

I think this way is better than keeping and checking expiration time because that is a bit racy,qCheckMail can check time and found it to still be valid but the time could expire as soon as the check is done.

Can you confirm that it works so that i can close this bug report.

**Comment by vvv-ibm** [comment]
Seems to work fine, thanks!

I did notice that when I go to check the configuration for an existing
account, the "password is google's OAuth2 refresh token" is not checked and
there are no stars in the password field?
Despite that the notification seems to work.

**Comment by mhogomchungu** [comment]
The latest git version removed the bug noticed.

**Comment by vvv-ibm** [comment]
Yep, now it works, thanks!

**Comment by mhogomchungu** [comment]
closing this one as being "fixed" since both raised issues are now solved.
