### ISSUE TITLE
Consider a non-envelope icon when there is no unread mail

### ISSUE THREAD

**Issue by evmcl** [mhogomchungu/qCheckGMail#38]
Hi. Recently started using qCheckGMail which is working admirably. The one thing I find difficult it to easily distinguish the icons for when unread email is available or not.

I find seeing an envelope in my tray, no matter the colour or lack of animation, makes me think that there is always unread email. I keep doing a double-take which is a distraction.

In my local build of qCheckGMail, I replaced the envelope icon of grey.svg with a greyed version of [social-email-circular-button.svg](https://www.flaticon.com/free-icon/social-email-circular-button_56443) - <img alt="social-email-circular-button.svg" src="https://image.flaticon.com/icons/svg/56/56443.svg" width="24" height="24"> - which I found works really well for me.

**Comment by Maryse47** [comment]
I don't understand you - when there is unread mail there isn't only a color change but also a number of unread mails is shown, don't you see it?

Also in KDE grey icon (no new emails) is automatically hidden in tray (if it isn't, you may change it in tray preferences).

The icon you linked looks completely alien to me. I don't think it fits for the UI, at least not for default choice.

**Comment by mhogomchungu** [comment]
Its understandable different people may want different icons, will look into adding ability to change the icons.

**Comment by mhogomchungu** [comment]
It is now possible to change app icons by replacing the ones that are installed or by install custom icons as part of icon theme package(how sure how this works)

Location and names of installed icons when in /usr/ are
```
/usr/share/icons/qCheckGMail-hasNoMail.svg
/usr/share/icons/qCheckGMail-hasError.svg
 /usr/share/icons/qCheckGMail-hasMail.svg
```
