### ISSUE TITLE
Segfault at startup when building against lxqt_wallet 3.2.1

### ISSUE THREAD

**Issue by Maryse47** [mhogomchungu/qCheckGMail#42]
When qcheckgmail is build against latest release of lxqt_wallet (externally with `-DINTERNAL_LXQT_WALLET=false` then it causes segfault at startup:

```
/usr/bin/qCheckGMail
[1]    64340 segmentation fault (core dumped)  /usr/bin/qCheckGMail
```
Using lxqt_wallet 3.1.0 works. Note that building with internal lxqt_wallet isn't possible: https://github.com/mhogomchungu/qCheckGMail/issues/39#issuecomment-473652697

Build environment:
qcheckgmail: ([latest commit](https://github.com/mhogomchungu/qCheckGMail/commit/3a4d01ada1c36059dc655743f4ccf62820a7d41c)
lxqt_wallet: 3.2.1
qt: 5.15.0
distro: Arch Linux
build commands:
```
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DINTERNAL_LXQT_WALLET=false \
        -DKF5=true

make
```

**Comment by mhogomchungu** [comment]
qCheckGMail will have to be rebuild against lxqt_wallet >= 3.2.0 because lxqt_wallet changed its API.

update qCheckGMail from git and try again.

Are you using this project? I can not use it here because it hasn't passed google's verification process.

**Comment by Maryse47** [comment]
Now the build fail the same with both external and internal lxqt_wallet:
```
[100%] Linking CXX executable qCheckGMail
/usr/bin/ld: cannot find -lQt5::DBus
```

> Are you using this project? I can not use it here because it hasn't passed google's verification process.

It's possible to allow unverified app access in google account settings.

**Comment by mhogomchungu** [comment]
Update from git and try again.

I did not know it was possible to allow unverified app access. Just tried it and it worked!! Thanks for the tip.

**Comment by Maryse47** [comment]
Thx, everything works now. I think this deserves new release.
