### ISSUE TITLE
New mail tray icon distracting after update to KDE plasma 5.22

### ISSUE THREAD

**Issue by Maryse47** [mhogomchungu/qCheckGMail#44]
After update to KDE Plasma 5.22 from 5.21 in ArchLinux the frequency at which new mail tray icon _bounces_ is way too high which causes distraction for user. Previously the tray icon _bounced_ more slowly which was ok.

I have no idea why update made such weird behavior change but I hope the old frequency can be restored or animation disabled completely as present behavior is quite unbearable when new mail arrives.

Tested on https://github.com/mhogomchungu/qCheckGMail/commit/886e5f83b52345758745f3ea158ed44e891b47fb

```
Operating System: Arch Linux
KDE Plasma Version: 5.22.1
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Graphics Platform: X11
```

**Comment by mhogomchungu** [comment]
I can not reproduce this, do you still have this problem with the latest version of plasma? The latest version is 5.22.2

**Comment by Maryse47** [comment]
Yes, it still happens. It may depend on panel/icon size, scaling, panel position (I have vertical one) or whatever. I recored a video to demonstrate the problem:

https://user-images.githubusercontent.com/41080948/123540894-cfd24c80-d730-11eb-977b-8d1554999c4a.mp4

Would it be possible to add option that disables tray icon animation?

**Comment by Maryse47** [comment]
I found out the way to reproduce it:

System settings (kde desktop tool) -> Workspace Behavior -> General Behavior -> Animation Speed -> Instant (slide max to the right). You need to restart qcheckgmail to take effect.

The more you slide it to the left, the more bounce freq decreases. Obviously it affects all plasma animations but as I didn't have any other app that animate its tray icon in such way the issue only affected qcheckgmail.

As slower animations make desktop feel more sluggish in general I would still appreciate option to disable tray animations which isn't critical to have and would save me from tweaking global desktop settings to fix one app. Please consider.

**Comment by mhogomchungu** [comment]
Done.

1. Update from git.
2. Run the app.
3. Look at its config file located at "~/.config/qCheckGMail/qCheckGMail.conf" and you will see a new entry named "visibleIconState". The option can take 3 different options and they are named "NeedsAttention","Active" and "Passive". the first one is the default and i think the option you want is "Active". 
4. Set the option to "Active".
5. Restart the app.

These options are documented here: https://api.kde.org/frameworks/knotifications/html/classKStatusNotifierItem.html#a5a724a726f39f52275ee62e1fe2ff539

**Comment by Maryse47** [comment]
Confirmed it works as I wanted. Many thx for help.
